// Generated by tools/tokens.ts from tokens/*.tokens.json. Do not edit; edit the tokens.

/** Resolved token values in the light appearance. */
export const tokens = {
  "color": {
    "system": {
      "red": "#FF383C",
      "orange": "#FF8D28",
      "yellow": "#FFCC00",
      "green": "#34C759",
      "mint": "#00C8B3",
      "teal": "#00C3D0",
      "cyan": "#00C0E8",
      "blue": "#0088FF",
      "indigo": "#6155F5",
      "purple": "#CB30E0",
      "pink": "#FF2D55",
      "brown": "#AC7F5E"
    },
    "gray": {
      "1": "#8E8E93",
      "2": "#AEAEB2",
      "3": "#C7C7CC",
      "4": "#D1D1D6",
      "5": "#E5E5EA",
      "6": "#F2F2F7"
    },
    "label": {
      "primary": "#000000",
      "secondary": "#3C3C4399",
      "tertiary": "#3C3C434C",
      "quaternary": "#3C3C432E"
    },
    "fill": {
      "primary": "#78788033",
      "secondary": "#78788029",
      "tertiary": "#7676801F",
      "quaternary": "#74748014"
    },
    "background": {
      "primary": "#FFFFFF",
      "secondary": "#F2F2F7",
      "tertiary": "#FFFFFF"
    },
    "groupedBackground": {
      "primary": "#F2F2F7",
      "secondary": "#FFFFFF",
      "tertiary": "#F2F2F7"
    },
    "separator": {
      "translucent": "#3C3C434A",
      "opaque": "#C6C6C8"
    },
    "accent": "#0088FF"
  },
  "device": {
    "display": {
      "outer": {
        "width": "466px",
        "height": "678px",
        "scale": 3,
        "radiusFree": "59px",
        "radiusHinge": "8px"
      },
      "inner": {
        "width": "951px",
        "height": "669px",
        "scale": 3,
        "radius": "55px",
        "foldBand": "27px"
      },
      "pointsPerMillimeter": 6.02
    },
    "finish": {
      "starWhite": {
        "frame": "#F2EEE5",
        "antenna": "#BCB8B3",
        "hingeCover": "#F2EFE7",
        "back": "#FFFDF8",
        "backMetalness": 0,
        "backClearcoat": 0,
        "flash": "#F7F0E6",
        "sensor": "#FCF5EB",
        "buttonFace": "#F3F1EE",
        "buttonFaceMetalness": 0.8,
        "screw": "#F2F1F0"
      },
      "nightSky": {
        "frame": "#3F4B59",
        "antenna": "#072433",
        "hingeCover": "#2F3A4B",
        "back": "#1D3545",
        "backMetalness": 0.2,
        "backClearcoat": 1,
        "flash": "#1E3748",
        "sensor": "#10222E",
        "buttonFace": "#0D2130",
        "buttonFaceMetalness": 0.2,
        "screw": "#3F4B59"
      }
    }
  },
  "material": {
    "glass": {
      "tint": 0.5,
      "tintStops": [
        0,
        0.25,
        0.5,
        0.75,
        1
      ],
      "sizeStops": [
        56,
        76,
        96,
        150,
        180
      ],
      "sizeBlur": 9.82,
      "lensSoften": 1.962,
      "curve": {
        "levels": [
          0,
          9,
          19,
          28,
          38,
          47,
          57,
          66,
          76,
          85,
          94,
          104,
          113,
          123,
          132,
          142,
          151,
          161,
          170,
          179,
          189,
          198,
          208,
          217,
          227,
          236,
          246,
          255
        ],
        "regularDark": [
          [
            32,
            41,
            50,
            59,
            68,
            75,
            84,
            91,
            99,
            105,
            112,
            119,
            125,
            131,
            136,
            142,
            147,
            152,
            156,
            160,
            165,
            168,
            172,
            175,
            178,
            180,
            183,
            185
          ],
          [
            32,
            41,
            50,
            59,
            68,
            75,
            84,
            91,
            99,
            105,
            112,
            119,
            125,
            131,
            136,
            142,
            147,
            152,
            156,
            160,
            165,
            168,
            172,
            175,
            178,
            180,
            183,
            185
          ],
          [
            32,
            41,
            50,
            59,
            68,
            75,
            84,
            91,
            99,
            105,
            112,
            119,
            125,
            131,
            136,
            142,
            147,
            152,
            156,
            160,
            165,
            168,
            172,
            175,
            178,
            180,
            183,
            185
          ],
          [
            28,
            35,
            42,
            48,
            55,
            60,
            67,
            72,
            78,
            83,
            88,
            93,
            97,
            102,
            106,
            110,
            114,
            118,
            121,
            124,
            127,
            130,
            133,
            135,
            137,
            139,
            141,
            142
          ],
          [
            32,
            36,
            41,
            45,
            50,
            54,
            58,
            61,
            65,
            69,
            72,
            75,
            78,
            81,
            84,
            87,
            89,
            92,
            94,
            96,
            98,
            100,
            102,
            103,
            105,
            106,
            107,
            108
          ]
        ],
        "regularLight": [
          [
            102,
            108,
            114,
            119,
            125,
            131,
            137,
            143,
            149,
            154,
            160,
            165,
            171,
            177,
            182,
            188,
            193,
            199,
            204,
            210,
            215,
            220,
            226,
            231,
            237,
            242,
            247,
            252
          ],
          [
            117,
            122,
            128,
            133,
            138,
            143,
            149,
            154,
            159,
            164,
            169,
            174,
            179,
            185,
            189,
            195,
            199,
            205,
            209,
            214,
            219,
            224,
            229,
            233,
            238,
            243,
            248,
            252
          ],
          [
            132,
            137,
            142,
            146,
            151,
            156,
            161,
            165,
            170,
            174,
            179,
            183,
            188,
            192,
            197,
            201,
            205,
            210,
            214,
            218,
            223,
            227,
            232,
            236,
            240,
            244,
            249,
            253
          ],
          [
            155,
            159,
            163,
            167,
            171,
            174,
            178,
            182,
            186,
            189,
            193,
            197,
            200,
            204,
            207,
            211,
            215,
            218,
            222,
            225,
            229,
            232,
            236,
            239,
            243,
            246,
            250,
            253
          ],
          [
            178,
            181,
            184,
            187,
            190,
            193,
            196,
            199,
            202,
            204,
            207,
            210,
            213,
            216,
            218,
            221,
            224,
            227,
            229,
            232,
            235,
            237,
            240,
            243,
            245,
            248,
            251,
            253
          ]
        ],
        "clear": [
          32,
          40,
          50,
          59,
          68,
          77,
          86,
          95,
          104,
          113,
          122,
          131,
          140,
          149,
          158,
          167,
          176,
          186,
          194,
          203,
          212,
          221,
          231,
          239,
          249,
          255,
          255,
          255
        ]
      },
      "regular": {
        "blur": [
          1.48,
          2.09,
          3.2,
          4.33,
          9.03
        ],
        "wideShare": [
          0.26,
          0.431,
          0.626,
          0.762,
          0.844
        ],
        "saturation": [
          1.21,
          1.18,
          1.18,
          0.9,
          0.63
        ],
        "sizeShare": [
          0,
          0.07,
          0.261,
          0.765,
          0.854
        ],
        "lens": 17.0122,
        "lensPower": 0.9967,
        "bezelRatio": 0.4513,
        "profile": 0.28,
        "rim": 0.3946,
        "ior": 1.5,
        "bezel": 10,
        "lensSizePower": 0.5,
        "dispersion": 0.4,
        "frost": 1,
        "shadow": 0.02
      },
      "clear": {
        "blur": [
          0.39,
          0.95,
          1.3,
          3.67,
          8.87
        ],
        "wideShare": [
          0,
          0,
          0,
          0.376,
          0.916
        ],
        "saturation": [
          1.06,
          1.06,
          1.06,
          1,
          0.94
        ],
        "sizeShare": [
          0,
          0,
          0,
          0,
          0
        ],
        "lens": 16.5645,
        "bezelRatio": 0.6329,
        "profile": 0.3468,
        "lensPower": 0.9967,
        "rim": 0.7453,
        "ior": 1.5,
        "bezel": 10,
        "lensSizePower": 0.5,
        "dispersion": 0.5,
        "frost": 1,
        "shadow": 0.02
      },
      "hairline": {
        "multiply": 0.3785,
        "subtract": 0.3052,
        "width": 0.75,
        "lightTop": 0.3
      },
      "blurWide": 16,
      "container": {
        "spacing": 10
      },
      "flipArea": 0,
      "toneDark": "#1F1F1F",
      "toneLight": "#FFFFFF"
    }
  },
  "motion": {
    "spring": {
      "smooth": {
        "bounce": 0,
        "duration": 500
      },
      "snappy": {
        "bounce": 0.15,
        "duration": 500
      },
      "bouncy": {
        "bounce": 0.3,
        "duration": 500
      },
      "hinge": {
        "bounce": 0,
        "duration": 900
      },
      "glance": {
        "bounce": 0.1,
        "duration": 350
      },
      "cameraSettle": {
        "bounce": 0.05,
        "duration": 700
      }
    },
    "duration": {
      "instant": "100ms",
      "quick": "200ms",
      "standard": "350ms",
      "deliberate": "600ms",
      "ambient": "2000ms"
    },
    "easing": {
      "standard": [
        0.25,
        0.1,
        0.25,
        1
      ],
      "linear": [
        0,
        0,
        1,
        1
      ]
    }
  },
  "presentation": {
    "stageHero": {
      "fontFamily": [
        "system-ui",
        "-apple-system",
        "sans-serif"
      ],
      "fontSize": "80px",
      "fontWeight": 600,
      "lineHeight": "84px",
      "letterSpacing": "-0.015em"
    },
    "stageHeadline": {
      "fontFamily": [
        "system-ui",
        "-apple-system",
        "sans-serif"
      ],
      "fontSize": "48px",
      "fontWeight": 600,
      "lineHeight": "52px",
      "letterSpacing": "-0.003em"
    },
    "stageKicker": {
      "fontFamily": [
        "system-ui",
        "-apple-system",
        "sans-serif"
      ],
      "fontSize": "22px",
      "fontWeight": 600,
      "lineHeight": "28px",
      "letterSpacing": "0.01em"
    },
    "stageBody": {
      "fontFamily": [
        "system-ui",
        "-apple-system",
        "sans-serif"
      ],
      "fontSize": "19px",
      "fontWeight": 400,
      "lineHeight": "27px",
      "letterSpacing": "0.006em"
    }
  },
  "space": {
    "0": "0px",
    "1": "2px",
    "2": "4px",
    "3": "8px",
    "4": "12px",
    "5": "16px",
    "6": "20px",
    "7": "24px",
    "8": "32px",
    "9": "40px",
    "10": "48px",
    "margin": {
      "compact": "16px",
      "regular": "20px"
    }
  },
  "size": {
    "hitTarget": "44px",
    "glassButton": "44px",
    "rail": "84px",
    "railInset": "48px",
    "railEdge": "24px",
    "railLead": "12px",
    "railButton": "48px",
    "railSymbol": "36px",
    "railGroupPad": "10px",
    "railGroupGap": "18px",
    "railGap": "12px",
    "railCameraGap": "6px",
    "cameraPunch": "43px",
    "cameraPunchHeight": "42px",
    "cameraLens": "37px",
    "cameraLensTop": "5.33px",
    "symbol": "24px",
    "symbolTab": "25.4px",
    "tabItem": "54px",
    "tabPad": "6px",
    "tabPill": "64px",
    "tabPillWidth": "44px",
    "tabSearchGap": "8px",
    "topBar": "82px",
    "topBarTitleX": "20px",
    "topBarTitleY": "37px",
    "sheetInset": "8px",
    "sheetRadius": "40px",
    "sheetRadiusTrailing": "48px",
    "sheetRadiusHinge": "8px",
    "sheetGrabber": "60px",
    "sidebar": "320px",
    "foldBand": "28px"
  },
  "radius": {
    "xs": "6px",
    "sm": "10px",
    "md": "16px",
    "lg": "26px",
    "capsule": "9999px",
    "concentricMin": "8px"
  },
  "stage": {
    "shadow": 0.55,
    "exposure": 1,
    "light": {
      "key": 7,
      "fill": 1.6,
      "rim": 5.5,
      "top": 4,
      "bounce": 1.4,
      "studio": 0.08
    },
    "camera": {
      "fov": {
        "default": 22,
        "tight": 18,
        "wide": 26
      },
      "fill": 0.6
    },
    "mood": {
      "black": {
        "sky": "#000000",
        "ground": "#000000",
        "ink": "dark",
        "env": "neutral",
        "intensity": 0,
        "exposure": 1,
        "turn": 0,
        "shadow": 0,
        "floor": "#000000",
        "floorStrength": 0
      },
      "night": {
        "sky": "#07080B",
        "ground": "#000000",
        "ink": "dark",
        "env": "cool",
        "intensity": 0.14,
        "exposure": 1,
        "turn": -6,
        "shadow": 0.35,
        "floor": "#1B2130",
        "floorStrength": 0.55
      },
      "dawn": {
        "sky": "#9DB0CF",
        "ground": "#E9D8CF",
        "ink": "light",
        "env": "cool",
        "intensity": 0.85,
        "exposure": 1,
        "turn": -16,
        "shadow": 0.45,
        "floor": "#FFFFFF",
        "floorStrength": 0
      },
      "morning": {
        "sky": "#F5F5F7",
        "ground": "#E6E6EB",
        "ink": "light",
        "env": "neutral",
        "intensity": 1,
        "exposure": 1,
        "turn": 0,
        "shadow": 0.5,
        "floor": "#FFFFFF",
        "floorStrength": 0
      },
      "day": {
        "sky": "#FBFBFD",
        "ground": "#E9ECF1",
        "ink": "light",
        "env": "neutral",
        "intensity": 1.15,
        "exposure": 1.02,
        "turn": 25,
        "shadow": 0.5,
        "floor": "#FFFFFF",
        "floorStrength": 0
      },
      "office": {
        "sky": "#E7ECF2",
        "ground": "#D5DDE6",
        "ink": "light",
        "env": "cool",
        "intensity": 1,
        "exposure": 1,
        "turn": 23,
        "shadow": 0.5,
        "floor": "#FFFFFF",
        "floorStrength": 0
      },
      "book": {
        "sky": "#F4EEE7",
        "ground": "#D8CBBD",
        "ink": "light",
        "env": "warm",
        "intensity": 0.95,
        "exposure": 1,
        "turn": -26,
        "shadow": 0.5,
        "floor": "#FFFFFF",
        "floorStrength": 0
      },
      "evening": {
        "sky": "#2B2119",
        "ground": "#0E0A07",
        "ink": "dark",
        "env": "warm",
        "intensity": 0.8,
        "exposure": 1,
        "turn": -75,
        "shadow": 0.6,
        "floor": "#6A4A2F",
        "floorStrength": 0.5
      },
      "dusk": {
        "sky": "#394452",
        "ground": "#171C24",
        "ink": "dark",
        "env": "cool",
        "intensity": 0.95,
        "exposure": 1,
        "turn": -20,
        "shadow": 0.5,
        "floor": "#394862",
        "floorStrength": 0.45
      },
      "title": {
        "sky": "#000000",
        "ground": "#000000",
        "ink": "dark",
        "env": "neutral",
        "intensity": 0.9,
        "exposure": 1,
        "turn": -35,
        "shadow": 0,
        "floor": "#000000",
        "floorStrength": 0
      },
      "twilight": {
        "sky": "#1E2A4A",
        "ground": "#4A3F55",
        "ink": "dark",
        "env": "cool",
        "intensity": 0.4,
        "exposure": 1,
        "turn": -16,
        "shadow": 0.4,
        "floor": "#3A3C56",
        "floorStrength": 0.35
      }
    }
  },
  "font": {
    "family": {
      "sans": [
        "system-ui",
        "-apple-system",
        "sans-serif"
      ],
      "rounded": [
        "ui-rounded",
        "SF Pro Rounded",
        "system-ui",
        "sans-serif"
      ],
      "serif": [
        "ui-serif",
        "New York",
        "serif"
      ],
      "mono": [
        "ui-monospace",
        "SF Mono",
        "Menlo",
        "monospace"
      ]
    }
  },
  "text": {
    "largeTitle": {
      "fontFamily": [
        "system-ui",
        "-apple-system",
        "sans-serif"
      ],
      "fontSize": "34px",
      "fontWeight": 400,
      "lineHeight": "41px",
      "letterSpacing": "0.012em"
    },
    "title1": {
      "fontFamily": [
        "system-ui",
        "-apple-system",
        "sans-serif"
      ],
      "fontSize": "28px",
      "fontWeight": 400,
      "lineHeight": "34px",
      "letterSpacing": "0.014em"
    },
    "title2": {
      "fontFamily": [
        "system-ui",
        "-apple-system",
        "sans-serif"
      ],
      "fontSize": "22px",
      "fontWeight": 400,
      "lineHeight": "28px",
      "letterSpacing": "-0.012em"
    },
    "title3": {
      "fontFamily": [
        "system-ui",
        "-apple-system",
        "sans-serif"
      ],
      "fontSize": "20px",
      "fontWeight": 400,
      "lineHeight": "25px",
      "letterSpacing": "-0.023em"
    },
    "headline": {
      "fontFamily": [
        "system-ui",
        "-apple-system",
        "sans-serif"
      ],
      "fontSize": "17px",
      "fontWeight": 590,
      "lineHeight": "22px",
      "letterSpacing": "-0.026em"
    },
    "body": {
      "fontFamily": [
        "system-ui",
        "-apple-system",
        "sans-serif"
      ],
      "fontSize": "17px",
      "fontWeight": 400,
      "lineHeight": "22px",
      "letterSpacing": "-0.026em"
    },
    "callout": {
      "fontFamily": [
        "system-ui",
        "-apple-system",
        "sans-serif"
      ],
      "fontSize": "16px",
      "fontWeight": 400,
      "lineHeight": "21px",
      "letterSpacing": "-0.020em"
    },
    "subheadline": {
      "fontFamily": [
        "system-ui",
        "-apple-system",
        "sans-serif"
      ],
      "fontSize": "15px",
      "fontWeight": 400,
      "lineHeight": "20px",
      "letterSpacing": "-0.016em"
    },
    "footnote": {
      "fontFamily": [
        "system-ui",
        "-apple-system",
        "sans-serif"
      ],
      "fontSize": "13px",
      "fontWeight": 400,
      "lineHeight": "18px",
      "letterSpacing": "-0.006em"
    },
    "caption1": {
      "fontFamily": [
        "system-ui",
        "-apple-system",
        "sans-serif"
      ],
      "fontSize": "12px",
      "fontWeight": 400,
      "lineHeight": "16px",
      "letterSpacing": "0.000em"
    },
    "caption2": {
      "fontFamily": [
        "system-ui",
        "-apple-system",
        "sans-serif"
      ],
      "fontSize": "11px",
      "fontWeight": 400,
      "lineHeight": "13px",
      "letterSpacing": "0.006em"
    }
  },
  "tracking": {
    "sfPro": [
      [
        6,
        41
      ],
      [
        7,
        34
      ],
      [
        8,
        26
      ],
      [
        9,
        19
      ],
      [
        10,
        12
      ],
      [
        11,
        6
      ],
      [
        12,
        0
      ],
      [
        13,
        -6
      ],
      [
        14,
        -11
      ],
      [
        15,
        -16
      ],
      [
        16,
        -20
      ],
      [
        17,
        -26
      ],
      [
        18,
        -25
      ],
      [
        19,
        -24
      ],
      [
        20,
        -23
      ],
      [
        21,
        -18
      ],
      [
        22,
        -12
      ],
      [
        23,
        -4
      ],
      [
        24,
        3
      ],
      [
        25,
        6
      ],
      [
        26,
        8
      ],
      [
        27,
        11
      ],
      [
        28,
        14
      ],
      [
        29,
        14
      ],
      [
        30,
        14
      ],
      [
        31,
        13
      ],
      [
        32,
        13
      ],
      [
        33,
        12
      ],
      [
        34,
        12
      ],
      [
        35,
        11
      ],
      [
        36,
        10
      ],
      [
        37,
        10
      ],
      [
        38,
        10
      ],
      [
        39,
        10
      ],
      [
        40,
        10
      ],
      [
        41,
        9
      ],
      [
        42,
        9
      ],
      [
        43,
        9
      ],
      [
        44,
        8
      ],
      [
        45,
        8
      ],
      [
        46,
        8
      ],
      [
        47,
        8
      ],
      [
        48,
        8
      ],
      [
        49,
        7
      ],
      [
        50,
        7
      ],
      [
        51,
        7
      ],
      [
        52,
        6
      ],
      [
        53,
        6
      ],
      [
        54,
        6
      ],
      [
        56,
        6
      ],
      [
        58,
        5
      ],
      [
        60,
        4
      ],
      [
        62,
        4
      ],
      [
        64,
        4
      ],
      [
        66,
        3
      ],
      [
        68,
        2
      ],
      [
        70,
        2
      ],
      [
        72,
        2
      ],
      [
        76,
        1
      ],
      [
        80,
        0
      ],
      [
        84,
        0
      ],
      [
        88,
        0
      ],
      [
        92,
        0
      ],
      [
        96,
        0
      ]
    ]
  }
} as const;

/** Values that change per appearance: dark, lightHC, darkHC. */
export const modes = {
  "color": {
    "system": {
      "red": {
        "dark": "#FF4245",
        "lightHC": "#E9152D",
        "darkHC": "#FF6165"
      },
      "orange": {
        "dark": "#FF9230",
        "lightHC": "#C55300",
        "darkHC": "#FFA056"
      },
      "yellow": {
        "dark": "#FFD600",
        "lightHC": "#A16A00",
        "darkHC": "#FEDF43"
      },
      "green": {
        "dark": "#30D158",
        "lightHC": "#008932",
        "darkHC": "#4AD968"
      },
      "mint": {
        "dark": "#00DAC3",
        "lightHC": "#008575",
        "darkHC": "#54DFCB"
      },
      "teal": {
        "dark": "#00D2E0",
        "lightHC": "#008198",
        "darkHC": "#3BDDEC"
      },
      "cyan": {
        "dark": "#3CD3FE",
        "lightHC": "#007EAE",
        "darkHC": "#6DD9FF"
      },
      "blue": {
        "dark": "#0091FF",
        "lightHC": "#1E6EF4",
        "darkHC": "#5CB8FF"
      },
      "indigo": {
        "dark": "#6D7CFF",
        "lightHC": "#564ADE",
        "darkHC": "#A7AAFF"
      },
      "purple": {
        "dark": "#DB34F2",
        "lightHC": "#B02FC2",
        "darkHC": "#EA8DFF"
      },
      "pink": {
        "dark": "#FF375F",
        "lightHC": "#E7124D",
        "darkHC": "#FF8AC4"
      },
      "brown": {
        "dark": "#B78A66",
        "lightHC": "#956D51",
        "darkHC": "#DBA679"
      }
    },
    "gray": {
      "1": {
        "dark": "#8E8E93",
        "lightHC": "#6C6C70",
        "darkHC": "#AEAEB2"
      },
      "2": {
        "dark": "#636366",
        "lightHC": "#8E8E93",
        "darkHC": "#7C7C80"
      },
      "3": {
        "dark": "#48484A",
        "lightHC": "#AEAEB2",
        "darkHC": "#545456"
      },
      "4": {
        "dark": "#3A3A3C",
        "lightHC": "#BCBCC0",
        "darkHC": "#444446"
      },
      "5": {
        "dark": "#2C2C2E",
        "lightHC": "#D8D8DC",
        "darkHC": "#363638"
      },
      "6": {
        "dark": "#1C1C1E",
        "lightHC": "#EBEBF0",
        "darkHC": "#242426"
      }
    },
    "label": {
      "primary": {
        "dark": "#FFFFFF"
      },
      "secondary": {
        "dark": "#EBEBF599"
      },
      "tertiary": {
        "dark": "#EBEBF54C"
      },
      "quaternary": {
        "dark": "#EBEBF529"
      }
    },
    "fill": {
      "primary": {
        "dark": "#7878805C"
      },
      "secondary": {
        "dark": "#78788052"
      },
      "tertiary": {
        "dark": "#7676803D"
      },
      "quaternary": {
        "dark": "#7676802E"
      }
    },
    "background": {
      "primary": {
        "dark": "#000000"
      },
      "secondary": {
        "dark": "#1C1C1E"
      },
      "tertiary": {
        "dark": "#2C2C2E"
      }
    },
    "groupedBackground": {
      "primary": {
        "dark": "#000000"
      },
      "secondary": {
        "dark": "#1C1C1E"
      },
      "tertiary": {
        "dark": "#2C2C2E"
      }
    },
    "separator": {
      "translucent": {
        "dark": "#54545899"
      },
      "opaque": {
        "dark": "#38383A"
      }
    },
    "accent": {
      "dark": "#0091FF"
    }
  }
} as const;

/** Springs with their CSS linear() form. Pass { bounce, duration } to Anime.js spring(). */
export const springs = {
  "smooth": {
    "bounce": 0,
    "duration": 500,
    "easing": "linear(0, 0.004 1%, 0.0087 1.5%, 0.0228 2.5%, 0.0421 3.5%, 0.0787 5%, 0.1068 6%, 0.153 7.5%, 0.3701 14%, 0.4647 17%, 0.5229 19%, 0.5636 20.5%, 0.6375 23.5%, 0.7011 26.5%, 0.7292 28%, 0.7633 30%, 0.8139 33.5%, 0.8597 37.5%, 0.8987 42%, 0.9301 47%, 0.9539 52.5%, 0.971 58.5%, 0.9833 65.5%, 0.9912 73.5%, 0.9959 83%, 1)",
    "settleMs": 734
  },
  "snappy": {
    "bounce": 0.15,
    "duration": 500,
    "easing": "linear(0, 0.0036 1%, 0.0211 2.5%, 0.0502 4%, 0.0746 5%, 0.1022 6%, 0.1483 7.5%, 0.1983 9%, 0.4102 15%, 0.5107 18%, 0.5727 20%, 0.6162 21.5%, 0.6948 24.5%, 0.762 27.5%, 0.7914 29%, 0.8264 31%, 0.8708 34%, 0.9115 37.5%, 0.9458 41.5%, 0.9696 45.5%, 0.9886 50.5%, 0.9998 56%, 1.0048 61.5%, 1.0063 68%, 1)",
    "settleMs": 696
  },
  "bouncy": {
    "bounce": 0.3,
    "duration": 500,
    "easing": "linear(0, 0.005 1%, 0.0111 1.5%, 0.0292 2.5%, 0.0545 3.5%, 0.1032 5%, 0.1615 6.5%, 0.2265 8%, 0.4822 13.5%, 0.592 16%, 0.6911 18.5%, 0.7445 20%, 0.7773 21%, 0.808 22%, 0.8498 23.5%, 0.8867 25%, 0.9188 26.5%, 0.9625 29%, 0.9833 30.5%, 1.0004 32%, 1.0217 34.5%, 1.0353 37%, 1.0438 40%, 1.046 43%, 1.0409 48%, 1.0122 62.5%, 1.0027 70.5%, 0.998 82.5%, 1)",
    "settleMs": 818
  },
  "hinge": {
    "bounce": 0,
    "duration": 900,
    "easing": "linear(0, 0.004 1%, 0.0087 1.5%, 0.0229 2.5%, 0.0422 3.5%, 0.0788 5%, 0.1069 6%, 0.1531 7.5%, 0.3704 14%, 0.465 17%, 0.5232 19%, 0.564 20.5%, 0.6378 23.5%, 0.7014 26.5%, 0.7295 28%, 0.7636 30%, 0.8142 33.5%, 0.8599 37.5%, 0.8989 42%, 0.9303 47%, 0.954 52.5%, 0.9711 58.5%, 0.9833 65.5%, 0.9912 73.5%, 0.9959 83%, 1)",
    "settleMs": 1322
  },
  "glance": {
    "bounce": 0.1,
    "duration": 350,
    "easing": "linear(0, 0.0033 1%, 0.0193 2.5%, 0.0458 4%, 0.0934 6%, 0.1355 7.5%, 0.1813 9%, 0.3929 15.5%, 0.4858 18.5%, 0.5841 22%, 0.6346 24%, 0.6697 25.5%, 0.7325 28.5%, 0.7604 30%, 0.794 32%, 0.844 35.5%, 0.8838 39%, 0.9026 41%, 0.9225 43.5%, 0.9501 48%, 0.9708 53%, 0.9861 59%, 0.9951 65.5%, 0.9999 73.5%, 1.0015 86%, 1)",
    "settleMs": 466
  },
  "cameraSettle": {
    "bounce": 0.05,
    "duration": 700,
    "easing": "linear(0, 0.0061 1.5%, 0.0226 3%, 0.0473 4.5%, 0.0899 6.5%, 0.167 9.5%, 0.3671 16.5%, 0.4628 20%, 0.5139 22%, 0.5619 24%, 0.6381 27.5%, 0.704 31%, 0.7601 34.5%, 0.8073 38%, 0.8463 41.5%, 0.8864 46%, 0.9199 51%, 0.9464 56.5%, 0.966 62.5%, 0.9798 69%, 0.9897 77%, 0.9953 85.5%, 1)",
    "settleMs": 848
  }
} as const;

export type SpringName = keyof typeof springs;

/** The CSS custom property for a token path, e.g. cssVar('color', 'system', 'blue'). */
export const cssVar = (...path: string[]) =>
  `var(--${path.map((p) => p.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()).join('-')})`;

/** SF Pro tracking in em for a point size, interpolated from Apple's table. */
export function trackingEm(sizePt: number): number {
  const table = tokens.tracking.sfPro as unknown as readonly (readonly [number, number])[];
  if (sizePt <= table[0][0]) return table[0][1] / 1000;
  for (let i = 1; i < table.length; i++) {
    const [s1, t1] = table[i];
    if (sizePt <= s1) {
      const [s0, t0] = table[i - 1];
      return (t0 + ((sizePt - s0) / (s1 - s0)) * (t1 - t0)) / 1000;
    }
  }
  return table[table.length - 1][1] / 1000;
}
