/**
 * Token compiler: app/tokens/*.tokens.json (DTCG) -> src/tokens/tokens.css + src/tokens/tokens.ts
 *
 * Run: `node tools/tokens.ts` (Node 24 strips the types), or let vite-plugin-tokens run it.
 *
 * Source format (W3C Design Tokens Community Group draft):
 *   - A token is an object with `$value`; `$type` may sit on the token or any ancestor group.
 *   - `$description` states where the value came from. The compiler warns when a token and all
 *     of its ancestors lack one, because every value must carry its provenance (AGENTS.md).
 *   - `{group.token}` references resolve against the merged tree, in values and in modes.
 *   - Appearance modes live in `$extensions["duo.modes"]` as { dark, lightHC, darkHC }.
 *
 * Outputs:
 *   - CSS custom properties, `--` + the kebab-cased path. Light values sit on `:root` and
 *     `[data-appearance="light"]`; mode values on `[data-appearance="dark"]` and the
 *     `[data-contrast="high"]` variants, so any subtree (a device screen) can switch appearance.
 *   - `.type-<style>` classes for every typography token.
 *   - For every spring, a CSS `linear()` easing and its settle duration, computed from the same
 *     perceptual spring model SwiftUI and Anime.js use, so CSS and JS motion match.
 *   - A TypeScript module with the resolved values, modes, and small typed helpers.
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
type JsonObject = { [key: string]: Json };
type Mode = 'dark' | 'lightHC' | 'darkHC';

export interface Token {
  path: string[];
  type: string;
  value: Json;
  modes: Partial<Record<Mode, Json>>;
  description?: string;
  extensions: JsonObject;
}

const MODES: Mode[] = ['dark', 'lightHC', 'darkHC'];
const MODE_SELECTORS: Record<'light' | Mode, string> = {
  light: ':root, [data-appearance="light"]',
  dark: '[data-appearance="dark"]',
  lightHC: '[data-appearance="light"][data-contrast="high"], :root[data-contrast="high"]',
  darkHC: '[data-appearance="dark"][data-contrast="high"]',
};

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const TOKENS_DIR = join(ROOT, 'tokens');
const OUT_DIR = join(ROOT, 'src', 'tokens');
const HEADER = 'Generated by tools/tokens.ts from tokens/*.tokens.json. Do not edit; edit the tokens.';

const isObject = (v: Json | undefined): v is JsonObject => typeof v === 'object' && v !== null && !Array.isArray(v);
const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
export const cssName = (path: string[]) => `--${path.map(kebab).join('-')}`;

// ---- Load and merge ---------------------------------------------------------------------------

function mergeInto(target: JsonObject, source: JsonObject, file: string, trail: string[] = []): void {
  for (const [key, value] of Object.entries(source)) {
    const here = [...trail, key];
    if (key in target) {
      if (isObject(target[key]) && isObject(value) && !('$value' in value)) {
        mergeInto(target[key] as JsonObject, value, file, here);
        continue;
      }
      throw new Error(`${file}: "${here.join('.')}" is already defined by another token file`);
    }
    target[key] = value;
  }
}

export function loadTree(dir = TOKENS_DIR): JsonObject {
  const tree: JsonObject = {};
  for (const file of readdirSync(dir).filter((f) => f.endsWith('.tokens.json')).sort()) {
    mergeInto(tree, JSON.parse(readFileSync(join(dir, file), 'utf8')) as JsonObject, file);
  }
  return tree;
}

// ---- Collect tokens -----------------------------------------------------------------------------

export function collect(tree: JsonObject): { tokens: Token[]; warnings: string[] } {
  const tokens: Token[] = [];
  const warnings: string[] = [];
  const walk = (node: JsonObject, path: string[], inheritedType?: string, described = false) => {
    const type = typeof node.$type === 'string' ? node.$type : inheritedType;
    const hasDescription = described || typeof node.$description === 'string';
    if ('$value' in node) {
      if (!type) throw new Error(`${path.join('.')}: no $type on the token or its groups`);
      if (!hasDescription) warnings.push(`${path.join('.')}: no $description here or on a parent group (provenance)`);
      const ext = isObject(node.$extensions) ? node.$extensions : {};
      const modes = isObject(ext['duo.modes']) ? (ext['duo.modes'] as Partial<Record<Mode, Json>>) : {};
      tokens.push({
        path, type, value: node.$value as Json, modes,
        description: typeof node.$description === 'string' ? node.$description : undefined,
        extensions: ext,
      });
      return;
    }
    for (const [key, child] of Object.entries(node)) {
      if (key.startsWith('$') || !isObject(child)) continue;
      walk(child, [...path, key], type, hasDescription);
    }
  };
  walk(tree, []);
  return { tokens, warnings };
}

// ---- References -------------------------------------------------------------------------------

const REF = /^\{([^}]+)\}$/;

export function resolveAll(tokens: Token[]): void {
  const byPath = new Map(tokens.map((t) => [t.path.join('.'), t]));
  const resolveValue = (value: Json, mode: 'light' | Mode, seen: string[]): Json => {
    if (typeof value === 'string') {
      const m = REF.exec(value);
      if (!m) return value;
      const target = byPath.get(m[1]);
      if (!target) throw new Error(`Unknown reference {${m[1]}} (from ${seen[0]})`);
      if (seen.includes(m[1])) throw new Error(`Reference cycle: ${[...seen, m[1]].join(' -> ')}`);
      const source = mode === 'light' ? target.value : (target.modes[mode] ?? fallbackMode(target, mode));
      return resolveValue(source, mode, [...seen, m[1]]);
    }
    if (Array.isArray(value)) return value.map((v) => resolveValue(v, mode, seen));
    if (isObject(value)) return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, resolveValue(v, mode, seen)]));
    return value;
  };
  for (const t of tokens) {
    const key = t.path.join('.');
    t.value = resolveValue(t.value, 'light', [key]);
    for (const mode of MODES) if (t.modes[mode] !== undefined) t.modes[mode] = resolveValue(t.modes[mode]!, mode, [key]);
  }
}

/** High-contrast modes fall back to their base appearance when a token defines none. */
function fallbackMode(t: Token, mode: Mode): Json {
  if (mode === 'darkHC') return t.modes.dark ?? t.value;
  return t.value;
}

// ---- Springs ------------------------------------------------------------------------------------

export interface SpringCurve { easing: string; settleMs: number }

/**
 * The perceptual spring model (WWDC23 "Animate with springs"; Anime.js 4.5 easings/spring):
 * stiffness = (2π / T)², damping = (1 - bounce) · 4π / T for bounce >= 0, mass = 1.
 * Returns the unit step response as a CSS linear() easing over its settle time.
 */
export function springCurve(bounce: number, durationMs: number): SpringCurve {
  const T = durationMs / 1000;
  const w0 = (2 * Math.PI) / T;
  const zeta = bounce >= 0 ? 1 - bounce : 1 / (1 + bounce);
  const x = (t: number): number => {
    if (zeta < 1) {
      const wd = w0 * Math.sqrt(1 - zeta * zeta);
      return 1 - Math.exp(-zeta * w0 * t) * (Math.cos(wd * t) + ((zeta * w0) / wd) * Math.sin(wd * t));
    }
    if (zeta === 1) return 1 - Math.exp(-w0 * t) * (1 + w0 * t);
    const r1 = -w0 * (zeta - Math.sqrt(zeta * zeta - 1));
    const r2 = -w0 * (zeta + Math.sqrt(zeta * zeta - 1));
    return 1 - (r2 * Math.exp(r1 * t) - r1 * Math.exp(r2 * t)) / (r2 - r1);
  };
  // Settle: the last moment the response is more than 0.1% away from rest, sampled at 1 ms.
  let settle = 0;
  for (let ms = 0; ms <= durationMs * 6; ms++) if (Math.abs(1 - x(ms / 1000)) > 0.001) settle = ms;
  settle = Math.max(settle, 1);
  const samples: [number, number][] = [];
  for (let i = 0; i <= 200; i++) samples.push([i / 200, x((i / 200) * (settle / 1000))]);
  samples[samples.length - 1][1] = 1;
  const kept = simplify(samples, 0.0015);
  const stops = kept.map(([p, v], i) =>
    i === 0 || i === kept.length - 1 ? `${round(v)}` : `${round(v)} ${round(p * 100, 2)}%`);
  return { easing: `linear(${stops.join(', ')})`, settleMs: settle };
}

/** Ramer-Douglas-Peucker on the sampled curve, so linear() stays short without visible error. */
function simplify(points: [number, number][], tolerance: number): [number, number][] {
  if (points.length < 3) return points;
  const [a, b] = [points[0], points[points.length - 1]];
  let worst = 0, index = 0;
  for (let i = 1; i < points.length - 1; i++) {
    const [px, py] = points[i];
    const t = (px - a[0]) / (b[0] - a[0]);
    const d = Math.abs(py - (a[1] + t * (b[1] - a[1])));
    if (d > worst) { worst = d; index = i; }
  }
  if (worst <= tolerance) return [a, b];
  return [...simplify(points.slice(0, index + 1), tolerance).slice(0, -1), ...simplify(points.slice(index), tolerance)];
}

const round = (n: number, digits = 4) => Number(n.toFixed(digits)).toString();

// ---- CSS ----------------------------------------------------------------------------------------

const quoteFamily = (f: string) => (/^[a-z-]+$/.test(f) ? f : `"${f}"`);

/** CSS declarations for one token in one mode. Composite types expand into several properties. */
function cssDeclarations(t: Token, value: Json): [string, string][] {
  const name = cssName(t.path);
  switch (t.type) {
    case 'color':
    case 'dimension':
    case 'duration':
      return [[name, String(value)]];
    case 'number':
      return [[name, String(value)]];
    case 'fontFamily':
      return [[name, (value as string[]).map(quoteFamily).join(', ')]];
    case 'cubicBezier':
      return [[name, `cubic-bezier(${(value as number[]).join(', ')})`]];
    case 'typography': {
      const v = value as JsonObject;
      const emphasized = t.extensions['duo.emphasizedWeight'];
      const out: [string, string][] = [
        [`${name}-size`, String(v.fontSize)],
        [`${name}-line-height`, String(v.lineHeight)],
        [`${name}-weight`, String(v.fontWeight)],
        [`${name}-letter-spacing`, String(v.letterSpacing)],
      ];
      if (emphasized !== undefined) out.push([`${name}-weight-emphasized`, String(emphasized)]);
      return out;
    }
    case 'duo.material':
      return Object.entries(value as JsonObject).map(([k, v]) => [`${name}-${kebab(k)}`, String(v)]);
    case 'duo.spring': {
      const { bounce, duration } = value as { bounce: number; duration: number };
      const curve = springCurve(bounce, duration);
      return [[`${name}-easing`, curve.easing], [`${name}-duration`, `${curve.settleMs}ms`]];
    }
    default:
      return []; // Types without a CSS form (for example duo.trackingTable) are TypeScript-only.
  }
}

function typographyClasses(tokens: Token[]): string {
  return tokens.filter((t) => t.type === 'typography').map((t) => {
    const name = cssName(t.path);
    const cls = `.type-${t.path.slice(1).map(kebab).join('-')}`;
    const family = (t.value as JsonObject).fontFamily;
    const familyVar = Array.isArray(family) ? `var(--font-family-sans)` : String(family);
    return `${cls} {\n  font-family: ${familyVar};\n  font-size: var(${name}-size);\n  line-height: var(${name}-line-height);\n` +
      `  font-weight: var(${name}-weight);\n  letter-spacing: var(${name}-letter-spacing);\n}\n` +
      (t.extensions['duo.emphasizedWeight'] !== undefined ? `${cls}.is-emphasized { font-weight: var(${name}-weight-emphasized); }\n` : '');
  }).join('\n');
}

export function toCss(tokens: Token[]): string {
  const blocks: string[] = [`/* ${HEADER} */\n`];
  const block = (selector: string, decls: [string, string][]) =>
    decls.length ? `${selector} {\n${decls.map(([k, v]) => `  ${k}: ${v};`).join('\n')}\n}\n` : '';
  blocks.push(block(MODE_SELECTORS.light, tokens.flatMap((t) => cssDeclarations(t, t.value))));
  for (const mode of MODES) {
    const decls = tokens.filter((t) => t.modes[mode] !== undefined || (mode === 'darkHC' && t.modes.dark !== undefined))
      .flatMap((t) => cssDeclarations(t, t.modes[mode] ?? fallbackMode(t, mode)));
    blocks.push(block(MODE_SELECTORS[mode], decls));
  }
  // Family values in typography tokens are references like "{font.family.sans}", already resolved;
  // classes point at the family variable so appearance scopes can override it.
  blocks.push(typographyClasses(tokens.map((t) => t.type === 'typography'
    ? { ...t, value: { ...(t.value as JsonObject), fontFamily: 'var(--font-family-sans)' } } : t)));
  return blocks.join('\n');
}

// ---- TypeScript ---------------------------------------------------------------------------------

function setPath(target: JsonObject, path: string[], value: Json) {
  let node = target;
  for (const key of path.slice(0, -1)) node = (node[key] ??= {}) as JsonObject;
  node[path[path.length - 1]] = value;
}

export function toTs(tokens: Token[]): string {
  const values: JsonObject = {};
  const modes: JsonObject = {};
  const springs: JsonObject = {};
  for (const t of tokens) {
    setPath(values, t.path, t.value);
    if (Object.keys(t.modes).length) setPath(modes, t.path, t.modes as JsonObject);
    if (t.type === 'duo.spring') {
      const { bounce, duration } = t.value as { bounce: number; duration: number };
      setPath(springs, [t.path[t.path.length - 1]], { bounce, duration, ...springCurve(bounce, duration) });
    }
  }
  const json = (v: Json) => JSON.stringify(v, null, 2);
  return `// ${HEADER}

/** Resolved token values in the light appearance. */
export const tokens = ${json(values)} as const;

/** Values that change per appearance: dark, lightHC, darkHC. */
export const modes = ${json(modes)} as const;

/** Springs with their CSS linear() form. Pass { bounce, duration } to Anime.js spring(). */
export const springs = ${json(springs)} as const;

export type SpringName = keyof typeof springs;

/** The CSS custom property for a token path, e.g. cssVar('color', 'system', 'blue'). */
export const cssVar = (...path: string[]) =>
  \`var(--\${path.map((p) => p.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()).join('-')})\`;

/** SF Pro tracking in em for a point size, interpolated from Apple's table. */
export function trackingEm(sizePt: number): number {
  const table = tokens.tracking.sfPro as unknown as readonly (readonly [number, number])[];
  if (sizePt <= table[0][0]) return table[0][1] / 1000;
  for (let i = 1; i < table.length; i++) {
    const [s1, t1] = table[i];
    if (sizePt <= s1) {
      const [s0, t0] = table[i - 1];
      return (t0 + ((sizePt - s0) / (s1 - s0)) * (t1 - t0)) / 1000;
    }
  }
  return table[table.length - 1][1] / 1000;
}
`;
}

// ---- Entry ------------------------------------------------------------------------------------

export function compile(): { warnings: string[]; count: number } {
  const { tokens, warnings } = collect(loadTree());
  resolveAll(tokens);
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(join(OUT_DIR, 'tokens.css'), toCss(tokens));
  writeFileSync(join(OUT_DIR, 'tokens.ts'), toTs(tokens));
  return { warnings, count: tokens.length };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const { warnings, count } = compile();
  for (const w of warnings) console.warn(`warning: ${w}`);
  console.log(`tokens: ${count} compiled -> src/tokens/tokens.css, src/tokens/tokens.ts`);
}
